source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'kuaishou' do
    pod 'Alamofire', '~> 4.5’
    pod 'SnapKit', '~> 4.0.0'
    pod 'LFLiveKit', '~> 2.6'
    pod 'SQLite.swift', '~> 0.11.4'
end
